codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: nearest
  range: "60...100"

  status:
    project:
      default:
        target: 80%
        if_ci_failed: error
    patch:
      default:
          target: 0%
    changes: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no

github_checks:
  annotations: false