jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3

    - name: Build Docs
      uses: mattnotmitt/doxygen-action@v1.9.5
      with:
        working-directory: .
        doxyfile-path: './docs/Doxyfile-mcss'

    - name: Create Directory
      run: |
        mkdir ./public
        cp -r ./html/* ./public
    
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: './public'